### ISSUE TITLE
Won't execute

### ISSUE THREAD

**Issue by aksdjlkasndlkasd** [victornpb/deleteDiscordMessages#1]
After hitting Start I get this error in console

VM81:171 Uncaught (in promise) TypeError: Cannot read property 'type' of undefined
    at <anonymous>:171:65
    at Array.filter (<anonymous>)
    at recurse (<anonymous>:171:47)
    at async deleteMessages (<anonymous>:249:16)

**Comment by victornpb** [comment]
Try again with the latest revision

**Comment by victornpb** [comment]
This was probably fixed in later commits
