### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by bababoei** [victornpb/deleteDiscordMessages#103]
running the script gives me this and i cant go any further, what's the problem?
![Capture](https://user-images.githubusercontent.com/68646329/88175476-8fb83f00-cc2e-11ea-8109-6c024e4c6fd8.PNG)

**Comment by gAVINpentesting** [comment]
Attempt to use the copy paste version! If that error happens, that version will likely work for you.

**Comment by victornpb** [comment]
This looks oddly familiar with Internet Explorer which doesn't support most ES6 features, if that's the case try using Chrome/Firefox.

I'll NOT make the script compatible with old browsers as it would significantly decrease readability, and for something like this it is important that people are able too read it and audit the code.

**Comment by llacb47** [comment]
I'm pretty sure this person just double clicked on the JS file and didn't read instructions.
