### ISSUE TITLE
[Question] Is there a betterdiscord plugin?

### ISSUE THREAD

**Issue by moom0o** [victornpb/deleteDiscordMessages#106]
> WARNING: Github Issues are publicly visible, do not post sensitive information here.
> You may want to use the "Screenshot mode" before taking screenshots or copying logs.

Describe what your question is, try to give as much detail as possible so I can help you.

Is there a betterdiscord plugin?

**Comment by gAVINpentesting** [comment]
At this current time I do not think so, as I'd assume the change of source code could disturb Victor's code? I'm unsure, but I'd say just disable BD until after you're done with Undiscord if it becomes wonky on you. Hopefully this insight may help you.

**Comment by victornpb** [comment]
No, and I haven't tested, so I'm not aware of any incompatibilities.
But it should work just fine as this script is standalone, the only thing that could break it, is if you for some reason remove/modify the top bar, where the trash button is added.

**Comment by victornpb** [comment]
if you have any further questions issues feel free to open a new one.

**Comment by hellbound1337** [comment]
You could instead use https://github.com/hellbound1337/clear-messages (Powercord Plugin)
More info on powercord: https://powercord.dev/
