### ISSUE TITLE
Can not run script?

### ISSUE THREAD

**Issue by XeroShift** [victornpb/deleteDiscordMessages#14]
Hello, 
 Was wondering if I could get a little help with an error message i'm receiving when attempting to run this script.  I posted an image below. Any help is greatly appreciated.

![image](https://user-images.githubusercontent.com/55376728/64937577-bb0d1900-d828-11e9-8ee4-fccae7c667fe.png)

**Comment by victornpb** [comment]
You have to copy everything from this link https://raw.githubusercontent.com/victornpb/deleteDiscordMessages/master/deleteDiscordMessages.js

Use <kbd>CTRL</kbd>-<kbd>A</kbd> to select everything then <kbd>CTRL</kbd>-<kbd>C</kbd> to Copy.

What browser are you using?

**Comment by XeroShift** [comment]
Hello, 
I feel like such a noob ...
I didn't realize I had to paste everything in... I was pasting "deleteDiscordMessages.js" ... doh!
