### ISSUE TITLE
Script tries to delete system messages

### ISSUE THREAD

**Issue by Perflyst** [victornpb/deleteDiscordMessages#15]
If you run the script in a direct chat group, this script tries to delete system message which contents are "Perflyst added xxx to the group."
`
Error deleting message, API responded with status 403!	{"message":"Cannot execute action on a system message","code":50021}
Related object:	{"hit":true,"attachments":[],"tts":false,"embeds":[],"timestamp":"201xxxxxx","mention_everyone":false,"id":"xx","pinned":false,"edited_timestamp":null,"author":{"username":"Perflyst","discriminator":"xx","id":"xx","avatar":"xxxx"},"mention_roles":[],"content":"","channel_id":"xx","mentions":[{"username":"User2","discriminator":"xx","id":"xx","avatar":"xx"}],"type":1}
`

**Comment by victornpb** [comment]
Thanks for reporting, **It's fixed now**.

I was only considering CALL messages as systems messages, it turns out there's a bunch more [types of systems messages](https://discordapp.com/developers/docs/resources/channel#message-object-message-types).
