### ISSUE TITLE
Alternative 

### ISSUE THREAD

**Issue by wathhr** [victornpb/deleteDiscordMessages#151]
**Is your feature request related to a problem? Please describe.**
To me opening my web browser of choice is a pain just to open the discord website whilst I already have the discord app open.

**Describe the solution you'd like**
It would be very nice if you could basically make this into a program (kinda like Discord Chat Exporter)

**Describe alternatives you've considered**
Another alternative I thought of is to make something like this into a Powercord or BetterDiscord plugin (I personally think Powercord is the better choice)
 
**Additional context**
This is basically what the program could look like:
https://wather.is-inside.me/ZwmV93Tk.png (taken straight from "Discord Chat Exporter") 

The plugin could just add 1 command, when executed it will delete all the messages in the channel you used it in. (really simple to make in Powercord, BetterDiscord I'm not sure) The plugin could also just be exactly what the script does, just adds a button to the top-bar of discord.

Update: A plugin for Powercord actually already exists (https://github.com/slow/message-cleaner) for the people looking back on this wanting to install this plugin I suggest cloning the repo instead of git cloning it, considering the creator of the plugin has some history.

**Comment by RayKoopa** [comment]
Ctrl+Shift+I in app, paste the [deletion source](https://raw.githubusercontent.com/victornpb/deleteDiscordMessages/master/deleteDiscordMessages.js) in Console, press Enter.
Warning, apparently outdated; adjust default deletion delay to 1000 ms or youll get rate limited.

**Comment by wathhr** [comment]
> Ctrl+Shift+I in app, paste the [deletion source](https://raw.githubusercontent.com/victornpb/deleteDiscordMessages/master/deleteDiscordMessages.js) in Console, press Enter.
> Warning, apparently outdated; adjust default deletion delay to 1000 ms or youll get rate limited.

Thanks but, that's still not very useful for me, no need to worry tho; somebody has already made the plugin I was looking for. Much appreciated!
