### ISSUE TITLE
[Question] Can I delete my messages from servers I am not in anymore?

### ISSUE THREAD

**Issue by stevengrullon06** [victornpb/deleteDiscordMessages#169]
Can I delete my messages from Discord servers that I left or got kicked/banned from? I have all of my credentials and channels/message IDs but the script won't work, leaving a "Missing Access" error along with code "50001"

**Comment by AirikWarren** [comment]
This is expected behavior. The script is only able to delete things that you would be able to delete manually yourself, it just does it faster.

**Comment by stevengrullon06** [comment]
> This is expected behavior. The script is only able to delete things that you would be able to delete manually yourself, it just does it faster.

Ah, I see. Thanks for the clarification
