### ISSUE TITLE
403 Issue!

### ISSUE THREAD

**Issue by Afrojack21** [victornpb/deleteDiscordMessages#17]
I can easily delete my own messages, but cannot delete other users messages on DM. Havin issue like this.

![image](https://user-images.githubusercontent.com/56152968/66194435-ba7fd980-e694-11e9-9f62-c18ba4ea1284.png)

**Comment by victornpb** [comment]
By design you can't delete messages from other people, unless you have a role to `manage messages`, this is not a bug.
