### ISSUE TITLE
[BUG] "GET" buttons not working on "Authorisation" or "Author"

### ISSUE THREAD

**Issue by MClara96** [victornpb/deleteDiscordMessages#229]
> WARNING: Github Issues are publicly visible, do not post sensitive information here.
> You may want to use the "Screenshot mode" before taking screenshots or copying logs.

**Describe the bug**
Clicking "authorisation" or "author" does not populate the fields, meaning the tool cannot be used
Edit: It works on Chrome

**To Reproduce**
1. Click the trashbin icon to display the tool
2. Click on GET next to Authorisation or Author
3. Nothing happens

**Affects** (Add an X to items that apply)
- [ X] DMs
- [X ] DM Groups
- [ X] Channel
- [X ] Channel (NSFW)
- [ X] Server (All Channels)
- [ ] Other (explain)

**System:**
 - OS: Windows 10
 - Browser: Firefox

**Comment by JLuke2600** [comment]
I'm also experiencing this issue on Windows 10, Firefox.

**Comment by gqqjhffr** [comment]
I'm having the exact same issue. Firefox on Windows 10.

**Comment by Mantas-2155X** [comment]
This is because of "Enhanced Tracking Protection" on Firefox. 
Disabling that on the discord site solves the issue and the buttons work for me again.
