### ISSUE TITLE
[Question] "Aborted by you"

### ISSUE THREAD

**Issue by KBZIZI** [victornpb/deleteDiscordMessages#230]
Hello,

I was trying to delete messages but whenever I click on "Start" it aborts itself for no reason, thus, not deleting any messages. That has happened on DM. Here's a screenshot:
https://i.ibb.co/cXt9swb/Screenshot-109.png

Thanks!

**Comment by KBZIZI** [comment]
I've followed the step on the readme.md "Undiscord" and it works again!

For those who had the same problem as me, you can try it.

**Comment by Heycate** [comment]
Where is the readme.md ?

**Comment by Toby222** [comment]
The readme is displayed right at the bottom of the repo
https://github.com/victornpb/deleteDiscordMessages
Alternatively, in the file listing at the same link
https://github.com/victornpb/deleteDiscordMessages/blob/master/readme.md

**Comment by victornpb** [comment]
I'm closing this since the instructions are much simpler now. If this still an issue please reopen.

**Comment by RushilShandilya** [comment]
Hey , I am facing the same issue.
Couldn't find the solution here.
