### ISSUE TITLE
[Question] Why aren't messages I send in threads able to delete?

### ISSUE THREAD

**Issue by grizzlybearclaws** [victornpb/deleteDiscordMessages#234]
When I try to delete my messages from threads, I get the error code below:
```
Error searching messages, API responded with status 403!
	{"message":"Missing Access","code":50001}
```
Can anyone explain to me in technical detail why messages I send in a thread aren't able to delete and why the API responds with status 403?

**Comment by Toby222** [comment]
The script is searching for messages in the thread, which doesn't seem to be a thing you can do
You can only search in normal text channels, and messages in any thread of that channel will still show up there

**Comment by grizzlybearclaws** [comment]
> The script is searching for messages in the thread, which doesn't seem to be a thing you can do
> You can only search in normal text channels, and messages in any thread of that channel will still show up there

Thanks, it works.
