### ISSUE TITLE
[Question] Use list of messages ID as delete list for server I left ?

### ISSUE THREAD

**Issue by Aperture77** [victornpb/deleteDiscordMessages#243]
Hello,

I downloaded my Discord data.
There are a lot of things  that I would like to remove and things that I want to keep.
A very high number of channel ID in index.json as marked as "null", meaning that I left the server associated, so I cannot delete them as I need the guild ID and not only the channel ID.
However for these null channel, I do have my messages history in messages.csv with the ID associated to each message.

My question is, if somehow I filter all the messages ID that I want to delete, can I delete them without having guild and channel ID. And if yes, can Undiscord app do it ? As for now the only feature with message ID is delete within a range, but not a specific list of ID.

Thanks, have a nice day !

**Comment by grizzlybearclaws** [comment]
You cannot delete messages without having a guild ID or channel ID. The Undiscord userscript needs those IDs.

**Comment by Aperture77** [comment]
> 
> 
> You cannot delete messages without having a guild ID or channel ID. The Undiscord userscript needs those IDs.

Ok, that a weird way of working for Discord. Before I close the issue, I suppose there is no way of finding the guild ID based on the channel ID ?

**Comment by grizzlybearclaws** [comment]
> > You cannot delete messages without having a guild ID or channel ID. The Undiscord userscript needs those IDs.
> 
> Ok thanks, that's a weird way of working for Discord. Before I close the issue, I suppose there is no way of finding the guild ID based on the channel ID ?

No, not that I know of.
