### ISSUE TITLE
[Question] Using Bot Token and Deleteting All Messages

### ISSUE THREAD

**Issue by r1bnc** [victornpb/deleteDiscordMessages#255]
> WARNING: Github Issues are publicly visible, do not post sensitive information here.
> You may want to use the "Screenshot mode" before taking screenshots or copying logs.

Describe what your question is, try to give as much detail as possible so I can help you.

Post screenshots if applicable.

How do I use this with a bot token? To avoid self-botting.
The bot has access to all messages, how to also delete all those messages or specific (ex. from webhooks).

**Comment by NathanKassab** [comment]
Discord doesn't care about self botting unless it's destructive (mass advertising), so you shouldn't even worry about that. Also it's impossible to tell it was a selfbot and not a human deleting a ton of messages so you would have an almost 0% risk of getting termed. But if you really want to use the bot just try putting the bot token and seeing what happens, do keep in mind it might not work. Some api endpoints are only accessible by users and some only by bots, if this project is programmed to use user endpoints then a bot might not be able to run it. Also I'm not sure if this project deletes just your messages or all messages, so it my not delete anything with a bot. Finally if you just want to wipe a discord channel then you can just get a nuke bot (clones the channel and deletes the old one)
