### ISSUE TITLE
[BUG] Only 25 messages to be deleted?

### ISSUE THREAD

**Issue by DevWannabe-dot** [victornpb/deleteDiscordMessages#257]
**Describe the bug**
If there is input for "after message with ID / before message with ID", it simply won't work. **Says API returned an empty page** or searches for like 117 messages but **only deletes 25** and aborts, without any of the messages having been deleted in the meantime.

**To Reproduce**
1. Go to a server and channel of your choice;
2. Fill in the authorization, guild ID and after message with ID / before message blanks.
3. See error
4. Retry with the ID of the channel selected
5. See error
6. Retry changing the message IDs to the previous or next message for both the cases, extending or shortening the total to be deleted by 2 messages;
![image](https://user-images.githubusercontent.com/64389041/134156452-fcbfc6c0-2f63-465f-96cf-ae039e7f21e5.png)
7. See error

**Screenshots / Logs**
![image](https://user-images.githubusercontent.com/64389041/134157566-000da1e3-5fd6-482e-abf8-5dc848960801.png)
![image](https://user-images.githubusercontent.com/64389041/134155635-42a981c1-db6f-49a5-b9fa-20e5fcc713f8.png)

```
Started at 21/09/2021, 07:41:36
authorId="REDACTED" guildId="REDACTED" channelId="REDACTED" minId="REDACTED" maxId="REDACTED" hasLink=false hasFile=false
Total messages found: 117	(Messages in current page: 25, To be deleted: 25, System: 0)	offset: 0
Delete delay: 1000ms, Search delay: 100ms	Last Ping: 235ms, Average Ping: 235ms
Estimated time remaining: 0h 2m 24s
Waiting for your confirmation...
OK
0.85% (1/117)	Deleting ID:REDACTED REDACTED (REDACTED): REDACTED	
1.71% (2/117)	Deleting ID:REDACTED REDACTED (REDACTED): REDACTED	
2.56% (3/117)	Deleting ID:REDACTED REDACTED (REDACTED): REDACTED	
3.42% (4/117)	Deleting ID:REDACTED REDACTED (REDACTED): REDACTED	
4.27% (5/117)	Deleting ID:REDACTED REDACTED (REDACTED): REDACTED	
5.13% (6/117)	Deleting ID:REDACTED REDACTED (REDACTED): REDACTED	
5.98% (7/117)	Deleting ID:REDACTED REDACTED (REDACTED): REDACTED	
6.84% (8/117)	Deleting ID:REDACTED REDACTED (REDACTED): REDACTED	
7.69% (9/117)	Deleting ID:REDACTED REDACTED (REDACTED): REDACTED	
8.55% (10/117)	Deleting ID:REDACTED REDACTED (REDACTED): REDACTED	
9.40% (11/117)	Deleting ID:REDACTED REDACTED (REDACTED): REDACTED	
10.26% (12/117)	Deleting ID:REDACTED REDACTED (REDACTED): REDACTED	
11.11% (13/117)	Deleting ID:REDACTED REDACTED (REDACTED): REDACTED	
11.97% (14/117)	Deleting ID:REDACTED REDACTED (REDACTED): REDACTED	
12.82% (15/117)	Deleting ID:REDACTED REDACTED (REDACTED): REDACTED	
13.68% (16/117)	Deleting ID:REDACTED REDACTED (REDACTED): REDACTED	
14.53% (17/117)	Deleting ID:REDACTED REDACTED (REDACTED): REDACTED	
15.38% (18/117)	Deleting ID:REDACTED REDACTED (REDACTED): REDACTED	
16.24% (19/117)	Deleting ID:REDACTED REDACTED (REDACTED): REDACTED	
17.09% (20/117)	Deleting ID:REDACTED REDACTED (REDACTED): REDACTED	
17.95% (21/117)	Deleting ID:REDACTED REDACTED (REDACTED): REDACTED	
18.80% (22/117)	Deleting ID:REDACTED REDACTED (REDACTED): REDACTED	
19.66% (23/117)	Deleting ID:REDACTED REDACTED (REDACTED): REDACTED	
20.51% (24/117)	Deleting ID:REDACTED REDACTED (REDACTED): REDACTED	
21.37% (25/117)	Deleting ID:REDACTED REDACTED (REDACTED): REDACTED	
Searching next messages in 100ms...	
Total messages found: 117	(Messages in current page: 0, To be deleted: 0, System: 0)	offset: 0
Delete delay: 1000ms, Search delay: 100ms	Last Ping: 252ms, Average Ping: 225ms
Estimated time remaining: 0h 2m 23s
Ended because API returned an empty page.
Ended at 21/09/2021, 07:42:13! Total time: 0h 0m 37s
Delete delay: 1000ms, Search delay: 100ms	Last Ping: 252ms, Average Ping: 225ms
Rate Limited: 0 times. Total time throttled: 0h 0m 0s.
Deleted 25 messages, 0 failed.
```

**Affects** (Add an X to items that apply)
- [ ] DMs
- [ ] DM Groups
- [X] Channel
- [ ] Channel (NSFW)
- [X] Server (All Channels)
- [ ] Other (explain)

**System:**
 - OS: Windows 10 21H1
 - Browser: Firefox 92.0 (64-bit)

**Comment by grimze** [comment]
same issue here, please let me know if you somehow manage to fix

**Comment by aurae-dc** [comment]
> same issue here, please let me know if you somehow manage to fix

^^

**Comment by crackychans** [comment]
Same

**Comment by phileezor** [comment]
Same here, been like that for the last month+ in my case

**Comment by dkoepke0** [comment]
same issue

**Comment by nazeling** [comment]
it works if you use "search messages"

**Comment by bottlesandeggs** [comment]
Same issue, would really love a fix 'cause I've got a lot of things I want to delete

**Comment by Teodric** [comment]
turning search delay to 200 seems to have fixed it for me

**Comment by DevWannabe-dot** [comment]
> turning search delay to 200 seems to have fixed it for me

it's in a cycle of 25 messages per time now, but it works, that's what matters :) thanks @Teodric I'll close it now, but anyone can feel free to comment
