### ISSUE TITLE
[Question] Does this work for Bot DMs?

### ISSUE THREAD

**Issue by FahadBinHussain** [victornpb/deleteDiscordMessages#264]
Does this script work for Bot Direct Messages(DM)? I want to clean some annoying messages from bots.

**Comment by Toby222** [comment]
You can only delete your own messages in a DM conversation

**Comment by FahadBinHussain** [comment]
Can't those messages be deleted from my side? That would be great! 😢

**Comment by Toby222** [comment]
Your own messages only. This script doesn't grant any extra permissions, it just automates the process.
If you can't delete it by hand, this script also can't delete it.
