### ISSUE TITLE
What is the bug on this? "Error deleting message, API responded with status 403! {"message":"Cannot execute action on a DM channel.", "code":50003}

### ISSUE THREAD

**Issue by alter-debug30** [victornpb/deleteDiscordMessages#268]
I am trying to delete a DM.

"Error deleting message, API responded with status 403! {"message":"Cannot execute action on a DM channel.", "code":50003}

**Comment by JinOfficial** [comment]
I have the same problem

**Comment by Toby222** [comment]
Are you trying to delete someone else's message?

**Comment by alter-debug30** [comment]
> Are you trying to delete someone else's message in a DM? In DMs, only the sender can delete messages, as there's no permission system there.

Yes, I am trying to delete someone else message.

**Comment by Toby222** [comment]
Well that's just not possible, due to how DMs work on Discord.
You'd have to ask the other person to delete their messages for you.

**Comment by victornpb** [comment]
Duplicated: https://github.com/victornpb/deleteDiscordMessages/issues/76
