### ISSUE TITLE
Can't delete messages from other people

### ISSUE THREAD

**Issue by JinOfficial** [victornpb/deleteDiscordMessages#270]
I can't delete messages from other people even though I entered the correct id
![image](https://user-images.githubusercontent.com/94340330/141723337-d0e7c4d3-8376-40d7-ab1b-639fe5fa04e1.png)

**Comment by Toby222** [comment]
As the error message states, you do not have permission to delete those messages.
Also note that there's a "screenshot mode" toggle that hides the things you manually scribbled out.

**Comment by victornpb** [comment]
Duplicated: https://github.com/victornpb/deleteDiscordMessages/issues/76
