### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by m-andries** [victornpb/deleteDiscordMessages#28]
When attempting to use the code, the following occurs:

Started at 12/7/2019, 11:53:50 PM
authorId="##################" guildId="@me" channelId="##################" afterMessageId="" beforeMessageId="" hasLink=false hasFile=false
Error searching messages, API responded with status 404!
	{"message":"404: Not Found","code":0}

**Comment by m-andries** [comment]
Additional error from console for reference:

GET https://discordapp.com/api/v6/channels/##################/messages/search?author_id=##################&sort_by=timestamp&sort_order=desc&offset=0 404

**Comment by Jyntax** [comment]
I have the exact same error and used scripts like these before so I know that auth, authorID and Channels are correct even if I'd type 'em in manually.

**Comment by Jyntax** [comment]
Got the answer I guess. Discord writes that their Search API is still offline and I guess that's the reason it doesn't work? https://status.discordapp.com/incidents/vs0q8cvycg46

**Comment by EwolBash** [comment]
@Jyntax yeah that's why it's not working and any other script will also not be working right now. Just need to wait unfortunately.
