### ISSUE TITLE
Error when attempting delete

### ISSUE THREAD

**Issue by Tani77** [victornpb/deleteDiscordMessages#29]
When attempting to delete, using the code, I get the following response

Error searching messages, API responded with status 404!
	{"message":"404: Not Found","code":0}

Not sure what the issue is, followed the readme

**Comment by Jyntax** [comment]
This happens because the search API of Discord is currently offline. So the script can't search for the messages.

**Comment by Tani77** [comment]
Thanks, appreciated

**Comment by briansaturnino** [comment]
Yeah, I'm having the same problem as well. 
Discord Search is recently not working. Many others are experiencing the same problem.
https://support.discordapp.com/hc/en-us/community/posts/360055565692-Search-function-not-working-and-is-always-showing-no-results-

**Comment by lucifudge** [comment]
Still not working.

**Comment by qyZMVYcw1VA6** [comment]
> Still not working.

I was able to use it last night. Currently I'm facing major API deletion delays (2 minutes!) but I figure it will be faster at some point in the future.
