### ISSUE TITLE
Deletes All or Some of the Messages

### ISSUE THREAD

**Issue by briansaturnino** [victornpb/deleteDiscordMessages#30]
On some accounts, it deletes only some of the messages. On other accounts, it deletes all of it. Why is this happening?

**Comment by qyZMVYcw1VA6** [comment]
What type of channel are you deleting messages in? (i.e., DMs with one user, group DMs, server text channels...)

**Comment by victornpb** [comment]
It will delete all messages you have privileges to delete.
