### ISSUE TITLE
Can i delete while keeping PMs?

### ISSUE THREAD

**Issue by rkk1995** [victornpb/deleteDiscordMessages#31]
I tried to find a way to do so but cant.

**Comment by qyZMVYcw1VA6** [comment]
Deletion is per text channel, per user. DMs will only be deleted by navigating to the DM you wish to remove your messages from, setting the Author by pressing the blue button ("Me") and pressing the blue button ("Get") for Guild/Channel, given that you have already grabbed your authorization token (by pressing the blue button, "Get," or obtaining it manually.)  You can only delete your own messages from DMs.

Deletion of messages in server text channels should **not** affect your DMs. If this is an issue you are facing, please provide any and all details that you can.

**Comment by victornpb** [comment]
@qyZMVYcw1VA6 is correct, thank you.
I'm closing this, OP is welcome to open a new issue if further help is needed.
