### ISSUE TITLE
No pop-up 

### ISSUE THREAD

**Issue by bwhieee** [victornpb/deleteDiscordMessages#33]
it allows me to paste the script but when I click enter here is no popup, just motif that Microsoft needs an app to read it, hen says Microsoft does not have apps to recommend. So I cant proceed. recomendations?

**Comment by qyZMVYcw1VA6** [comment]
What browser are you using?

**Comment by AxDSan** [comment]
Same issue here, apparently Discord wants to access an associated app that we don't know about, the recommendation is to search in the Microsoft Store, when Microsoft Store shows up, it is looking for apps that can open "about"

1
![image](https://user-images.githubusercontent.com/1641797/73200456-cccec900-4104-11ea-9c00-e943cf950b31.png)

2  
![image](https://user-images.githubusercontent.com/1641797/73200485-deb06c00-4104-11ea-8c2c-fc2cb6b4d3d2.png)

**Comment by AtkLordOverAll** [comment]
This happened for me when running the script in the Discord desktop app. The instructions specify that the JS script must be run in browser

**Comment by victornpb** [comment]
@alpha-tango-kilo you're right, It odens't work on the Electron App, it is currently only supported on the web version.

I don't plan into supporting it because It doesn't take more than a few seconds to login into discord using any browser.
