### ISSUE TITLE
[Request] Delete messages with specified word

### ISSUE THREAD

**Issue by Kikim25** [victornpb/deleteDiscordMessages#36]
Hello. I would like to thank author for this script, it's very useful and works well. I just have one problem.
My messages in a certain DM have over 100k messages so of course it will take very long to delete them all, so it is not ideal for me when I just really want to delete hundreds messages containing a certain word. E.g. I want it to look for my all messages in a DM that contain "foo" and delete them all. Is this possible at all? I understand what I am requesting for might be a lot of work or even impossible so I understand if it isn't doable. :) Thank you!

**Comment by victornpb** [comment]
The script is just limited to what it is possible to do with the discord search. What you're asking is doable, I'll add that since someone else also requested something similar.

**Comment by victornpb** [comment]
Solved in the latest version. You can now add a search term and it will only delete the messages found.
![image](https://user-images.githubusercontent.com/3372598/72034836-e783ef80-3274-11ea-9a2d-398483e22afa.png)
