### ISSUE TITLE
error 403 code 50001

### ISSUE THREAD

**Issue by buyingalife** [victornpb/deleteDiscordMessages#37]
Script working properly in DMs with people, but not working in a server where I am a mod and have all privileges, including "Manage Messages"

I am only trying to delete my own messages as well, so I'm not sure what could be giving this error.
![image](https://user-images.githubusercontent.com/28714083/71950377-f4d1a900-31a4-11ea-8113-3a5441a50c93.png)

**Comment by Kein** [comment]
NSFw channel?

**Comment by buyingalife** [comment]
it is nsfw channel, yes

**Comment by Kein** [comment]
Try:
https://pastebin.com/raw/KidL13yv

**Comment by Kein** [comment]
Seems like the author gets ID of the channel from the href/url bar instead of the guild object so he cant check if it is NSFW.
May be then it worth to add a extra checkbox for the user to tick so it will add NSFW argument to the query

**Comment by buyingalife** [comment]
tested by removing NSFW and this is correct.  script working after NSFW is removed

**Comment by victornpb** [comment]
Issue solved in #38

You can now select a option to include messages in NSFW channels
![image](https://user-images.githubusercontent.com/3372598/72034619-501e9c80-3274-11ea-9bc8-1da1a534eaa8.png)
