### ISSUE TITLE
Delete all messages from a guild returns a 404.

### ISSUE THREAD

**Issue by jtagcat** [victornpb/deleteDiscordMessages#44]
```
Total messages found: 4841	(Messages in current page: 25, Author: 25, System: 0)	offset: 0
Delete delay: 100ms, Search delay: 100ms	Last Ping: 1100ms, Average Ping: 1100ms
Estimated time remaining: 1h 37m 8s
Waiting for your confirmation...
OK
0.02% (1/4841)	Deleting ID:{id} {username} (1/17/2020, 1:11:20 PM\): {message}
Error deleting message, API responded with status 404!	{"message":"404: Not Found","code":0}
Related object:	{"id":"{id}","type":0,"content":"lol where did you get it?","channel_id":"358933713549262857","author":{"id":"516704923996651540","username":".Ras","avatar":"e2aa0383ad1293e516a85cabd08a0a89","discriminator":"5894"},"attachments":[],"embeds":[],"mentions":[],"mention_roles":[],"pinned":false,"mention_everyone":false,"tts":false,"timestamp":"2020-01-17T13:11:20.815000+00:00","edited_timestamp":null,"flags":0,"hit":true}
0.04% (2/4841)	Deleting ID:{id} {username} (1/17/2020, 1:05:59 PM\): {message}
Error deleting message, API responded with status 404!	{"message":"404: Not Found","code":0}
...
```
![httpcat404](https://http.cat/404)

**Comment by victornpb** [comment]
Is this a message from a DM chat, DM group, From a entire Server, a normal text channel, or nsfw channel?

**Comment by jtagcat** [comment]
Not a DM, entire server, guild id is filled in, channel id is left empty. Server had nsfw channels.

**Comment by KaKi87** [comment]
Hello, any news on this ? Thanks

**Comment by victornpb** [comment]
Sorry I haven't had time to work on this issue
Deleting channel by channel still works tho... I'll post here when I have a fix for this.

**Comment by KaKi87** [comment]
It would be nice, thanks. I have a few thousand messages to delete and working channel-by-channel isn't practical.

**Comment by victornpb** [comment]
Sorry for the long delay, but **this is fixed now**, you can just specify the Guild and leave the ChannelID blank, it will delete everything from that server. 

![image](https://user-images.githubusercontent.com/3372598/83704555-bf60a880-a5e8-11ea-859a-386e9aacb292.png)
