### ISSUE TITLE
popup.document.write is not a function

### ISSUE THREAD

**Issue by deathking61** [victornpb/deleteDiscordMessages#45]
VM231:6 Uncaught TypeError: popup.document.write is not a function
    at <anonymous>:6:20
    at <anonymous>:304:3us>:304:3

**Comment by victornpb** [comment]
What browser are you using?

**Comment by deathking61** [comment]
Chrome

**Comment by victornpb** [comment]
I wasn't able to reproduce this issue, this is most likely due to a popup blocker.
If this still happening please reopen.
