### ISSUE TITLE
The script isn't working anymore.

### ISSUE THREAD

**Issue by avacollab** [victornpb/deleteDiscordMessages#47]
I did use multiple revisions of this script in past and everything worked great however after trying to remove all my messages in one of the DM conversation I get an error: 
__________________________________________

> Do you want to delete ~1 messages?
> Estimated time: 0h 0m 0s
> 
> ---- Preview ----
> Myusername#1234: 

I get this error in both Firefox and Chrome. They are both latest version. The script log after error:

```
Started at 2/3/2020, 9:05:43 PM
authorId="123456" guildId="@me" channelId="123456" afterMessageId="" beforeMessageId="" hasLink=false hasFile=false
Total messages found: 1	(Messages in current page: 1, Author: 0, System: 1)	offset: 0
Delete delay: 100ms, Search delay: 100ms	Last Ping: 327ms, Average Ping: 327ms
Estimated time remaining: 0h 0m 0s
Waiting for your confirmation...
Aborted by you!
Ended at 2/3/2020, 9:06:38 PM! Total time: 0h 0m 54s
Delete delay: 100ms, Search delay: 100ms	Last Ping: 327ms, Average Ping: 327ms
Rate Limited: 0 times. Total time throttled: 0h 0m 0s.
Deleted 0 messages, 0 failed.
```

**Comment by victornpb** [comment]
I'll take a look, thanks for reporting

**Comment by Atrate** [comment]
It works on my end

**Comment by Glass47** [comment]
Script works, i can confirm that.
