### ISSUE TITLE
A wipe account option

### ISSUE THREAD

**Issue by FazerFox** [victornpb/deleteDiscordMessages#50]
an option that wipes all messages, leaves/deletes all servers and unfriends all friends however a filter would be nice so you can keep certain servers or friends

**Comment by grravity** [comment]
+1 to this

**Comment by KittyJutsu** [comment]
totally agree!

**Comment by namazso** [comment]
you can do this easier by requesting all your data from discord, then simply iterating over the messages

**Comment by victornpb** [comment]
#39 would fulfill this, but I'm waiting the author to make some changes in order to merge it

**Comment by KittyJutsu** [comment]
Great news!

**Comment by victornpb** [comment]
Merged in #88
