### ISSUE TITLE
 [FEEDBACK] I created a userscript for this.

### ISSUE THREAD

**Issue by itzTheMeow** [victornpb/deleteDiscordMessages#56]
I created a [userscript](https://greasyfork.org/en/scripts/398485-delete-discord-messages) for this. It adds this button: 
![image](https://user-images.githubusercontent.com/50887230/77273737-aeabc200-6c8a-11ea-9f25-e5e862423dd9.png)
to your toolbar. When you click it, it opens the delete messages in a new tab.

Hope it's useful :D

**Comment by Fahrenheit** [comment]
Thank you so much. Definitely useful as hell.

**Comment by gwennshinguji** [comment]
installing using GreaseMonkey outputs with this error.

`Ignoring @match pattern http*://*.discordapp.com/* because: Error: @match: Invalid protocol (http*:) specified.`

**Comment by MeowMeowCatPersonThing** [comment]
I've only tested it on TaperMonkey. I will update it later to fix for GreaseMonkey.

**Comment by victornpb** [comment]
I've been a bit reluctant in sharing this as a user script, my initial concerns was encouraging people to run anything on their accounts without checking it, this is why I tried to make all the code as transparent as possible. But I guess people like the convenience, so I might keep this up to date.

**Comment by MeowMeowCatPersonThing** [comment]
The userscript seems fairly popular lol

**Comment by llacb47** [comment]
Since this person deleted the issue, here is its former contents:

```
![image](https://user-images.githubusercontent.com/16567977/99590188-084fc200-29bb-11eb-968d-dcae72aa4af3.png)

and a link to the script:

https://gist.github.com/llacb47/38ea2a7ca8950620f6a1d7e6a32381d6

**Comment by itzTheMeow** [comment]
the point of deleting it is so the text wouldnt be there...

**Comment by victornpb** [comment]
Even tho I didn't take your code I was certainly inspired by this issue, specially the icon placement.
