### ISSUE TITLE
[BUG] Error searching messages, API responded with status 404! 	{"message":"404: Not Found","code":0}

### ISSUE THREAD

**Issue by yowee97** [victornpb/deleteDiscordMessages#58]
> WARNING: Github Issues are publicly visible, do not post sensitive information here.
> You may want to check "Hide sensitive information" before taking screenshots or copying logs.

Error searching messages, API responded with status 404!
	{"message":"404: Not Found","code":0}
whenever i put in the required info and try to delete DMs i get this message :(

**Comment by BluePlastics** [comment]
Same issue here, starting the script gives the exact same message.

**Comment by Inotamira** [comment]
I have a server to burn, and my old scripts aren't working either

**Comment by Glass47** [comment]
Same issue! Please fix!

**Comment by BMNJohn** [comment]
Same issue: it only works if I have a channel ID, but if I just want to clear a server and leave the channel ID field empty, it doesn't work.

**Comment by victornpb** [comment]
This bug was fixed, I can't  find the exact # tho
