### ISSUE TITLE
Suggestion: allow to queue deletion

### ISSUE THREAD

**Issue by AverytheFurry** [victornpb/deleteDiscordMessages#6]
Also, add a way to skip the current one (in case of infinite loop glitch) and to restart current or go back one (because sometimes it skips messages)

**Comment by AverytheFurry** [comment]
I mean I have 1,548 chats I want deleted from the face of the earth lol
![image](https://user-images.githubusercontent.com/47131867/64132140-61194780-cd82-11e9-9f07-93500b78c949.png)

**Comment by victornpb** [comment]
The range fields are there for that reason,
![image](https://user-images.githubusercontent.com/3372598/64138532-ce08fd80-cdd3-11e9-967f-5d5191f2a678.png)

If you want to delete messages, after or before a specific message you can just enter its ID. It can be a message from another person as well.

([How to find messageId](https://github.com/victornpb/deleteDiscordMessages/blob/master/help/messageId.md))

If this is not what you meant, please explain.
