### ISSUE TITLE
[BUG] Lag

### ISSUE THREAD

**Issue by Wralui** [victornpb/deleteDiscordMessages#62]
hello there, i have some lags when it starts to delete a huge amount of messages, over 2k for example
is there any way to avoid browser lagging while doing the process ? Is there memory leak or something doing that ? But i saw my browser never reach 2000Mb and 5% CPU and i cleared the logs.

**Comment by Wralui** [comment]
Ok i found out, when you lose the focus on the discord window it starts to slow down, you have to keep focus on discord dm for example, and if you close the console no more lags appear

**Comment by victornpb** [comment]
DevTools uses a fair amount of memory, as it keeps a lot of stuff in memory for debugging. After pasting the code and hitting enter you can close devtools to save memory. I might reduce the amount of console.logs
