### ISSUE TITLE
[Feature] Multithreading / multi delete

### ISSUE THREAD

**Issue by Wralui** [victornpb/deleteDiscordMessages#63]
Hi, is there any way to speed the process by doing multi threading for example ?
deleting message one by one is kinda slow, i was woundering if it is possible to make multitask or something like that to accelerate it
thanks

**Comment by jb184** [comment]
Likely not possible due to Discord rate-limiting

**Comment by victornpb** [comment]
It is not possible, and trying to circumvent this limitation would be detrimental to discord's  servers, which is not something I plan on doing.
