### ISSUE TITLE
Delete ONLY TEXT messages without attachments

### ISSUE THREAD

**Issue by luizgununes** [victornpb/deleteDiscordMessages#64]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I would like a checkbox to delete only text messages without attachments, like photos and videos. At the moment, we have a checkbox to delete only attachments, so I would like the opposite.

**Describe alternatives you've considered**
I've tried by myself to edit the script but no success. Maybe the owner could do it simple.

**Additional context**
No.

**Comment by victornpb** [comment]
This can't be easily done, unless the messages are queried without a filter and the filtered after the fact, but pagination is problematic as you have to keep track of the "do not delete" messages in every page
