### ISSUE TITLE
[Question] Is this project abandoned?

### ISSUE THREAD

**Issue by ShadowSocks12** [victornpb/deleteDiscordMessages#67]
-Where is the author?
-Where are the 2 contributes that are with the author in this project?
-Latest update was for readme.md    2 months ago.
-I currently see 22 Issues that are still not closed.
-Some issues don't even have an answer.
Is this the end of the project?

**Comment by victornpb** [comment]
No, it's just that I haven't had much free time since the world went bonkers.
I'll try to catch all the issues and PRs open.
