### ISSUE TITLE
[Question] What do I do if it says that it needs to open an "about link"?

### ISSUE THREAD

**Issue by nope8777** [victornpb/deleteDiscordMessages#68]
> WARNING: Github Issues are publicly visible, do not post sensitive information here.

Describe what your question is, try to give as much detail as possible so I can help you.

Post screenshots if applicable.

**Comment by victornpb** [comment]
If you're trying to use it on the discord app it will not work, you have to use discord web.
Other than that I would need more details on what is happening.
