### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Pifen1123** [victornpb/deleteDiscordMessages#69]
> WARNING: Github Issues are publicly visible, do not post sensitive information here.
> You may want to check "Hide sensitive information" before taking screenshots or copying logs.

**Describe the bug**

**To Reproduce**

**Screenshots / Logs**
If applicable, add screenshots and or copy log to help explain your problem.

```
Paste logs here
```Error deleting message, API responded with status 403!	{"message":"Cannot execute action on a DM channel","code":50003}

**Affects** (Add an X to items that apply)
- [x ] DMs
- [ ] DM Groups
- [ ] Channel
- [ ] Channel (NSFW)
- [ ] Server (All Channels)
- [Can't delete friends messages at dm channel ] Other (explain)

**System:**
 - OS: [e.g. Windows 10]
 - Browser [chrome]

**Comment by victornpb** [comment]
It is not possible to delete the other person's message in a DM channel.
This is a discord restriction and can't be circumvented in any other way.
