### ISSUE TITLE
Getting this error

### ISSUE THREAD

**Issue by Thedudeistt** [victornpb/deleteDiscordMessages#70]
VM240:6 Uncaught TypeError: popup.document.write is not a function
    at <anonymous>:6:20
    at <anonymous>:304:3
(anonymous) @ VM240:6
(anonymous) @ VM240:304

**Comment by victornpb** [comment]
Please provide extra information https://github.com/victornpb/deleteDiscordMessages/issues/new?assignees=&labels=&template=bug_report.md&title=%5BBUG%5D+
