### ISSUE TITLE
[BUG] Keep getting this error message when I am trying to delete Discord DMs 

### ISSUE THREAD

**Issue by HsRbx** [victornpb/deleteDiscordMessages#71]
When trying to delete my Discord DMs I keep getting this same error message in red, it'll delete for a bit then this error:
Search request throwed an error:	{"stack":"TypeError: Failed to fetch","message":"Failed to fetch"}

Help would be appreciated as soon as possible.

**Comment by victornpb** [comment]
Please provide extra information https://github.com/victornpb/deleteDiscordMessages/issues/new?assignees=&labels=&template=bug_report.md&title=%5BBUG%5D+

**Comment by ImportTaste** [comment]
This is caused by certain pop-up blocker extensions, which will essentially destroy the popup.document.write function on every page load, before any javascript has any chance to execute. For me, it was the extension 'Poper Blocker'.

**Comment by victornpb** [comment]
I'm considering implementing a version which doesn't need a separated window to avoid this kind of problem.
I would open inside the discord window, maybe on the side panel.
