### ISSUE TITLE
[Enhancement] Invert filter if possible

### ISSUE THREAD

**Issue by BourbonCrow** [victornpb/deleteDiscordMessages#77]
Not sure if possible but  currently filter deletes only what you select,, would it be possible to have the other way around as well like keep what is selected so i i select images it deletes all except images.. if its possibel could make a button that inverts that filter and makes them save instead of delete?

**Comment by victornpb** [comment]
Sorry, I don't have plans to implement this now, because it's not a common use case and it's not simple to create a reliable implementation. But I'm willing to accept a Pull request if someone submit a reliable algorithm.
