### ISSUE TITLE
[BUG] Search request throwed an error: {"stack":"TypeError: Failed to fetch","message":"Failed to fetch"}

### ISSUE THREAD

**Issue by HsRbx** [victornpb/deleteDiscordMessages#78]
I am attempting to delete my direct messages to someone on Discord, using the web app, on Windows 10. My wifi is good, nothing abnormal, there is around 9k dms left and it'll delete some and then other times when the API is searching I get this error message:
Search request throwed an error: {"stack":"TypeError: Failed to fetch","message":"Failed to fetch"}
And it stops, this only happens when it is searching for more messages, it deletes them fine, just has issues with searching.

**Comment by victornpb** [comment]
Try the new version and lmk if its works for you
