### ISSUE TITLE
I keep getting this error

### ISSUE THREAD

**Issue by Jetskiis** [victornpb/deleteDiscordMessages#79]
Error searching messages, API responded with status 403!
	{"message":"Missing Access","code":50001}

**Comment by victornpb** [comment]
You need to fill the Authorization token

**Comment by Jetskiis** [comment]
I filled the token, still doesn't work
Also theres no api v6 tab when i try to find it in network

**Comment by iacobiulian** [comment]
@Jetskiis Did you find a solution?

**Comment by iacobiulian** [comment]
Mark 'Delete NSFW'. That fixed it for me.

**Comment by Jetskiis** [comment]
Fixed, thanks ^^
