### ISSUE TITLE
[BUG] Error searching messages, API responded with status 404

### ISSUE THREAD

**Issue by Theoliane** [victornpb/deleteDiscordMessages#81]
Hi, this bug happened to me, before this happened, I could delete messages from dms etc but, I got this bug.

I went on discord google, pressed f12 to get access to the console, pasted the code, got the "menu" then did the usual steps, pressed get authorization, author, guild and channel.
I pressed start and this happened:

 Started at 14/06/2020 à 04:31:17
authorId="REDACTED" guildId="REDACTED" channelId="REDACTED" afterMessageId="REDACTED" beforeMessageId="REDACTED" hasLink=false hasFile=false
Error searching messages, API responded with status 404!
	{"message":"404: Not Found","code":0}
Here's a screenshot https://prnt.sc/szbpmw 

Thanks if you fix the problem.

**Comment by Kareem11222** [comment]
Same

**Comment by lol876** [comment]
I have the same problem. It's very annoying. Doesn't work on Chrome or any other browsers. Please fix it if you can soon thank you very much.

**Comment by illusion0001** [comment]
It's a discord issue, see here https://status.discord.com/incidents/zthbs4tmjt70

**Comment by lol876** [comment]
> It's a discord issue, see here https://status.discord.com/incidents/zthbs4tmjt70

It says the issue is resolved yet the script is not working, what is the reason?

**Comment by victornpb** [comment]
4.0 is out lmk if it is working for you
