### ISSUE TITLE
Wipe Messages In a specific "Date" Feature

### ISSUE THREAD

**Issue by Redactedd** [victornpb/deleteDiscordMessages#83]
Can you add a feature where you can select a specific "Date" And after you choose the specific date - every single message direct message you sent on that date will be deleted? You can do server messages if possible, If you did server messages that would be very helpful.

Aka,

_**----------------------------------------------------**_

[       ] - _No Date Selected_

[ 2018 ] - _Date Selected_

_Clicks Start_ 

All messages you sent in 2018 will be deleted - Every single conversation you had in 2018 will be deleted forever ( _*messages*_ )

**Results**

_Deleted more than 90 conversations you had with multiple people in 2018_

_**----------------------------------------------------**_

**Comment by Redactedd** [comment]
Updated.

**Comment by Redactedd** [comment]
Just for you to know this is a **_A wipe account option #50_** thing but instead of deleting every single message you sent in discord you can basically choose a specific date and then the code will start deleting every single message you sent in that date.

**Comment by victornpb** [comment]
I'm releasing this feature in a few minutes 
![image](https://user-images.githubusercontent.com/3372598/86522839-28cb1580-be3a-11ea-8cb6-d0f4606f1f1f.png)

**Comment by victornpb** [comment]
Added in #88

**Comment by victornpb** [comment]
Added option to choose a Before and After date.
#88

**Comment by Redactedd** [comment]
Thank you!
