### ISSUE TITLE
To delete a certain word throughout the channel

### ISSUE THREAD

**Issue by SSJBx** [victornpb/deleteDiscordMessages#86]
This feature is related to a problem of a discord server im in, there are a bunch of hard r's and that puts the server in risk, so id like to be able to mass delete all of them.

If a part where instead of deleting all messages by a certain user, you delete all messages containing the word; e.g: *WORD* - "Crap"
and it deletes all messages in that channel that include the word

An alternative could be throughout the whole server, as long as that word is no more to be found in the server.

Oh and if i can put in how many messages i would like to delete so i dont go over the deletion limit and get myself banned.

**Comment by SSJBx** [comment]
If this could get reviewed really soon, it would be extremely appreciated :DD

**Comment by victornpb** [comment]
This can currently be done, by using the `filter` it will only delete messages found using that search term.
If you want to delete from an entire server, just leave the `Channel` blank.

If you're a server admin, I suggest using a bot instead tho.

**Comment by SSJBx** [comment]
I have tried using bots but they dont go that far back, and I'd like to
know how to actually edit the filter in the script to do so if you can.
Thanks :)

**Comment by victornpb** [comment]
<img width="912" alt="image" src="https://user-images.githubusercontent.com/3372598/85228582-83845c00-b3ba-11ea-8662-2bed9988076f.png">

- Just put a word inside the `Containing text` box.
- When clicking **Get** "Guild/Channel", it fills both `Guild ID` and `Channel ID` automatically, just erase the `Channel ID` and leave it blank (to delete messages in every channel in that server).

**Comment by SSJBx** [comment]
[image: image.png] this comes up when i put it in my console
