### ISSUE TITLE
I wanna donate 350$ 

### ISSUE THREAD

**Issue by Redactedd** [victornpb/deleteDiscordMessages#87]
Can I donate 350$? And what's the donation link?

Thank you.

**Comment by ChaseHall** [comment]
[This link was found directly on the GitHub page.](https://www.buymeacoffee.com/vitim)

Pinging @victornpb to close.

**Comment by victornpb** [comment]
@Redactedd Thank you! That's is super generous of you.
https://www.buymeacoffee.com/vitim
