### ISSUE TITLE
Weird performance after cooldown from the ratelimit

### ISSUE THREAD

**Issue by lifehome** [victornpb/deleteDiscordMessages#9]
So when I hit the rate limit when deleting around 31 messages, the script doubles the delete delay timer to cool down. That's fine. But when we chilled a bit, and the time is up, the deleting process became very very slow.

My current approach is that delete 31 messages, stop it. Then wait 30 seconds or more, and restart the deletion. This way is much more a hassle, but more quicker compare to those slow snail-like deletion after chilled down from the rate limit.

Is there any chance to fix this issue?

**Comment by victornpb** [comment]
@lifehome I'll take a look. Can you share your Last ping, Ping average, and deleteDelay?

**Comment by lifehome** [comment]
<img width="912" alt="螢幕截圖 2019-09-10 下午10 34 49" src="https://user-images.githubusercontent.com/1886237/64628251-a218f800-d423-11e9-95a1-6b0c4e5233b6.png">
⬆️ Now this is where things go weird.

**Comment by chwba** [comment]
I had this run over night to delete 2k messages it deleted 343 in total, doesnt seem a lot

**Comment by victornpb** [comment]
You got cooled down for 90 seconds, that's a whole lot more than what I was getting before. On my tests I was getting cooled down for just a few milliseconds.

I added a less aggressive initial delay to 100ms (10th of a second).
Let me know if this makes it any better.

I don't really understand what is going on with the 404 errors, I have to investigate later.
Does all the `Related objects` have the same id: number, or are they different?  (Do not post the ID number.)

Does this message have a `type`? What number is it?

**Comment by chwba** [comment]
Im now in it with 2 accounts simultaneously, both fully cooled down. They deleted ~40 messages each and are now cooling down for 4 hours, is this normal?

**Comment by lifehome** [comment]
![image](https://user-images.githubusercontent.com/1886237/64854908-49c73d80-d651-11e9-8db8-0f432e6345b9.png)
Now the script with new version is running like this. Really jealous to @chwba :(

**Comment by lifehome** [comment]
![Screenshot_2019-09-13_at_18 10 11](https://user-images.githubusercontent.com/1886237/64855164-e38eea80-d651-11e9-975e-bc2c52ac4df6.png)
To depict better with some pictures at the console over the last few hours.

**Comment by lifehome** [comment]
Just an update, that I have never stopped the queue above (4 days ago), and it only deleted 2k messages... :frustrated:

**Comment by victornpb** [comment]
it is deleting messages once every ~2 minutes for you. I don't know why the API is hitting you with a very high limit. Can you delete messages manually without getting limited? Sorry I'm being very busy lately
