### ISSUE TITLE
[BUG] Trash bin icon does not show up in Safari

### ISSUE THREAD

**Issue by strafe** [victornpb/deleteDiscordMessages#91]
> WARNING: Github Issues are publicly visible, do not post sensitive information here.
> You may want to check "Hide sensitive information" before taking screenshots or copying logs.

**Describe the bug**
The trash bin icon is not visible when installing the user script version through Tampermonkey in Safari.

**To Reproduce**
1. Install the user script version using Tampermonkey in Safari.
2. Observe the trash bin icon not appearing in the top right.

**Screenshots / Logs**
<img width="1320" alt="image" src="https://user-images.githubusercontent.com/15663890/86545484-44601a00-bf27-11ea-9754-9df1ff468691.png">

```
N/A
```

**Affects** (Add an X to items that apply)
- [x] DMs
- [x] DM Groups
- [x] Channel
- [x] Channel (NSFW)
- [x] Server (All Channels)
- [x] Other (explain)

**System:**
 - OS: macOS 11.0 Big Sur
 - Browser: Safari 14.0

**Comment by victornpb** [comment]
thanks for reporting, I'll take a look later.

**Comment by victornpb** [comment]
I Just got the extension from the MacAppstore to find out it doesn't work. $2 wasted :(
This is a limitation of [Safari CSP and Tampermonkey extension](https://github.com/Tampermonkey/tampermonkey/issues/296#issuecomment-222356524)

I will remove Safari from the list, I don't want to waste people's money on Tampermonkey (from the AppStore).

If you really want to use Safari, the script will work just fine if you [paste it manually in the console](https://github.com/victornpb/deleteDiscordMessages/blob/master/help/copyPaste.md). But you'll have to paste it every time you want to use it.

**Comment by dennis777** [comment]
I think it works fine on safari if you use [Userscripts](https://apps.apple.com/us/app/userscripts/id1463298887) instead of Tampermonkey
